### ISSUE TITLE
flownetC6 pretrained model

### ISSUE THREAD

**Issue by sunnyHelen** [anuragranj/cc#13]
Hi, thank you for sharing the code. I downloaded your pretrained models. It seems there's no pretrained model for flownetC6. Could you please share it?

**Comment by anuragranj** [comment]
You can download it here:
https://www.dropbox.com/s/p37rz6x5vv8jn2d/flownet_model_best.pth.tar?dl=0

**Comment by sunnyHelen** [comment]
Thanks a lot
