### ISSUE TITLE
About correlation operation。

### ISSUE THREAD

**Issue by wenmingMeng** [anuragranj/cc#25]
https://github.com/anuragranj/cc/blob/2b4e36292c18f8ee68ad5d210a4190f9adf881dc/models/back2future.py#L174

Thanks for your sharing。Can you explain why use index_select function here？
The index_select remap the costvolume according to the idx_fwd 。This remap process is better for optical flow learning？

Looking forward to your reply。

**Comment by anuragranj** [comment]
This is to make it consistent with the lua-torch implementation of Back2Future https://github.com/JJanai/back2future . The Lua-torch correlation in JJanai/back2future is equivalent to remap->correlation in my implementation.
