### ISSUE TITLE
Details about the training algorithm

### ISSUE THREAD

**Issue by jmendozais** [anuragranj/cc#4]
Hi @anuragranj, I should say that your work is impressive!. I would like to implement your methods but I am confused with some details, and I will appreciate if you can give me some insights.

About the training algorithm, Are the first three initializations of pose/depth, flow, and motion are just one iteration, or several iterations of gradient descent?. On each iteration of the main loop, does each step (collaboration and competition) run 100K iterations? (I mean: 100K compet, 100K collab, 100K compet and so on.)

Thanks in advance,

**Comment by anuragranj** [comment]
This is correct: 100K compet, 100K collab, 100K compet and so on.

**Comment by MAGI-Yang** [comment]
Do we need to run 100K iterations to do the first three initializations of pose/depth, flow and camera motion, before the main loop?  
Or just 1 epoch is enough to do the initializations?

**Comment by anuragranj** [comment]
We need 100K iterations. 1 epoch is not enough.
