### ISSUE TITLE
Training script

### ISSUE THREAD

**Issue by charliememory** [anuragranj/cc#5]
Thanks for your nice work and code release. 
- I wonder if there is any script for the training procedure in Alg.1 of your paper? I followed your paper and wrote my own version (without ground truth) as follows. Is it correct?

```
python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
  --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.0 -m 0.0 -c 0.0 -s 0.1 \
  --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
  --epochs $epochs --smoothness-type edgeaware  --fix-masknet --fix-flownet \
  --log-terminal --name $EXPERIMENT_NAME 

## Train flownet
python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
  --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 0.0 -pf 1.0 -m 0.0 -c 0.0 -s 0.1 \
  --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
  --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet  --fix-masknet \
  --log-terminal --name $EXPERIMENT_NAME  --resume

## Train masknet
python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
  --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.5 -m 0.0 -c 0.0 -s 0.1 \
  --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
  --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet --fix-flownet \
  --log-terminal --name $EXPERIMENT_NAME  --resume

while true
do

    ## Train dispnet & posenet
    python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
      --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.5 -m 0.05 -c 0.0 -s 0.1 \
      --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
      --epochs $epochs --smoothness-type edgeaware  --fix-masknet --fix-flownet \
      --log-terminal --name $EXPERIMENT_NAME  --resume

    ## Train flownet
    python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
      --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 0.0 -pf 1.0 -m 0.005 -c 0.0 -s 0.1 \
      --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
      --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet  --fix-masknet \
      --log-terminal --name $EXPERIMENT_NAME  --resume

    ## Train masknet
    python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
      --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.5 -m 0.005 -c 0.3 -s 0.1 \
      --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
      --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet --fix-flownet \
      --log-terminal --name $EXPERIMENT_NAME  --resume

done
```

- Besides, I found that if `--fix-flownet` is not given in the script, then there will be an error. I wonder if it is caused by the flownet model.
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```

**Comment by anuragranj** [comment]
The script looks good. For training flow network for the first time, you would also need to set `--no-non-rigid-mask` so that it trains on the full image. And for training depth and pose for the first time, you can also remove `--fix-masknet -m 0.6`, which is equivalent to Zhou et al. CVPR 2017, and gives better results.

Which part of the script gives error if `--fix-flownet` is not specified? It could be because `-pf 0.0` is set, and might be causing some problem with pytorch. Read here:
https://discuss.pytorch.org/t/weighted-sum-of-two-losses-can-not-reduce-to-the-loss-of-one-component/20787

Moreover, these flow networks are often tricky to train. You could use a pretrained flow network using `--pretrained-flow /path/to/your/flow/network`. In our case, we trained FlowNetC from scratch, since no unsupervised pytorch model was available following the above script that you wrote. However, for the Back2Future Flow model we directly took the pretrained weights from Janai et al. ECCV 2018 and used it to learn other tasks.

**Comment by charliememory** [comment]
Thanks for your answers. 
Do you mean remove `--fix-masknet` and set `-m 0.6` for training depth and pose for the first time?

For the flownet, I think it's not caused by set `-pf 0.0`. I have tried to set all loss weights non-zero but doesn't work. I guess it is caused by the `Back2Future` network. Because when I switch to `FlowNetC6`, the error disappears.

The full error is as follows,
```
Traceback (most recent call last):
  File "train.py", line 826, in <module>
    main()
  File "train.py", line 375, in main
    train_loss = train(train_loader, disp_net, pose_net, mask_net, flow_net, optimizer, args.epoch_size, logger, training_writer)
  File "train.py", line 608, in train
    loss.backward()
  File "/path/to/miniconda3/envs/py36_tf_pytorch/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/path/to/miniconda3/envs/py36_tf_pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```

**Comment by anuragranj** [comment]
> remove --fix-masknet and set -m 0.6 for training depth and pose for the first time

Yes this is correct.

Can you paste the python command that you use that gives this error?

**Comment by charliememory** [comment]
The python command I used is 
```
python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
  --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 0.0 -pf 1.0 -m 0.0 -c 0.0 -s 0.1 \
  --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
  --epochs 2 --smoothness-type edgeaware  --fix-dispnet --fix-posenet  --fix-masknet \
  --name $EXPERIMENT_NAME
```

**Comment by anuragranj** [comment]
I can reproduce this error, but I still don't have a fix. It seems that there is an in-place operation in the model, that is causing this error. I still need to find where that is, to fix it.

**Comment by charliememory** [comment]
I finally figured out the reason. In the following lines, just change `vgrid[:,0,:,:]` to `vgrid[:,0,:,:].clone()`.
https://github.com/anuragranj/cc/blob/afd407869b89d61ee6911b13659e8d1c39dc3634/models/back2future.py#L306
https://github.com/anuragranj/cc/blob/afd407869b89d61ee6911b13659e8d1c39dc3634/models/back2future.py#L307

**Comment by anuragranj** [comment]
Thanks @charliememory . Fixed in https://github.com/anuragranj/cc/commit/941ba914771e356f49d13ebfe1623071f484df28

**Comment by siyuada** [comment]
Hey!
Thanks for you script for training, I just did the first initialization, but it takes 24 hours to train(RTX 2080). I wonder how many hours did you take to train the whole net?
(And it exists ``` while true ``` in your code, what's the stop criterion?)

Thanks a lot!

**Comment by anuragranj** [comment]
I took me about 7-8 days in total to train the whole thing from scratch on a Volta GPU.

**Comment by ezorfa** [comment]
Hi @anuragranj @charliememory @siyuada !

How is that while training masknet initially, we set m = 0.0 as in the script above ? :

`## Train masknet
python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
  --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.5 -m 0.0 -c 0.0 -s 0.1 \
  --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
  --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet --fix-flownet \
  --log-terminal --name $EXPERIMENT_NAME  --resume`

By setting m =0, we are effectively removing the term related to mask from loss fucntion, isnt it?

**Comment by xieenze** [comment]
hi @charliememory 
Can you reproduce the result training from scratch? 
Thanks

**Comment by xieenze** [comment]
@anuragranj Dear author, may you provide the full script to train from scratch? As shown in Alg.1 in the paper, instead of using pretrained model.

**Comment by anuragranj** [comment]
> Hi @anuragranj @charliememory @siyuada !
> 
> How is that while training masknet initially, we set m = 0.0 as in the script above ? :
> 
> `## Train masknet python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \ --masknet MaskNet6 --flownet Back2Future -b 4 -pc 1.0 -pf 0.5 -m 0.0 -c 0.0 -s 0.1 \ --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997 \ --epochs $epochs --smoothness-type edgeaware --fix-dispnet --fix-posenet --fix-flownet \ --log-terminal --name $EXPERIMENT_NAME --resume`
> 
> By setting m =0, we are effectively removing the term related to mask from loss fucntion, isnt it?

@ezorfa  You are right. It should be:
`python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
      --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.5 -m 0.005 -c 0.3 -s 0.1 \
      --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
      --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet --fix-flownet \
      --log-terminal --name $EXPERIMENT_NAME  --resume`

Actually m is just for the regularizer that forces m -> 1. Most of the training is due to consistency loss -c .

**Comment by anuragranj** [comment]
@xieenze You could use the following, as used by @charliememory .
```
python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
  --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.0 -m 0.6 -c 0.0 -s 0.1 \
  --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
  --epochs $epochs --smoothness-type edgeaware  --fix-flownet \
  --log-terminal --name $EXPERIMENT_NAME 

## Train flownet
python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
  --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 0.0 -pf 1.0 -m 0.0 -c 0.0 -s 0.1 \
  --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
  --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet  --fix-masknet \
  --log-terminal --no-non-rigid-mask --name $EXPERIMENT_NAME  --resume

## Train masknet
python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
 --masknet MaskNet6 --flownet Back2Future -b 4 -pc 1.0 -pf 0.5 -m 0.005 -c 0.3 -s 0.1 \ 
 --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997 \
 --epochs $epochs --smoothness-type edgeaware --fix-dispnet --fix-posenet --fix-flownet \
 --log-terminal --name $EXPERIMENT_NAME --resume

while true
do

    ## Train dispnet & posenet
    python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
      --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.5 -m 0.05 -c 0.0 -s 0.1 \
      --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
      --epochs $epochs --smoothness-type edgeaware  --fix-masknet --fix-flownet \
      --log-terminal --name $EXPERIMENT_NAME  --resume

    ## Train flownet
    python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
      --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 0.0 -pf 1.0 -m 0.005 -c 0.0 -s 0.1 \
      --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
      --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet  --fix-masknet \
      --log-terminal --name $EXPERIMENT_NAME  --resume

    ## Train masknet
    python3 train.py $data_root --dispnet DispResNet6 --posenet PoseNetB6 \
      --masknet MaskNet6 --flownet Back2Future  -b 4 -pc 1.0 -pf 0.5 -m 0.005 -c 0.3 -s 0.1 \
      --epoch-size 1000 --log-output -f 0 --nlevels 6 --lr 1e-4 -wssim 0.997  \
      --epochs $epochs --smoothness-type edgeaware  --fix-dispnet --fix-posenet --fix-flownet \
      --log-terminal --name $EXPERIMENT_NAME  --resume

done
```

**Comment by charliememory** [comment]
> hi @charliememory
> Can you reproduce the result training from scratch?
> Thanks

@xieenze, I did not follow up, as training from scratch does not coverage on my case. Maybe you can change the hyperparameters according to the authors' suggestion.
