### ISSUE TITLE
About GPU memory

### ISSUE THREAD

**Issue by zmlshiwo** [anuragranj/cc#6]
Hi, is single 1080Ti GPU (11GB) enough to train the whole model?

**Comment by anuragranj** [comment]
Yes, it should work. I have run it on 12GB Titan X with a batch-size 4, and the training works.

**Comment by zmlshiwo** [comment]
Thank you for the reply. Is the training code complete? I will try to train the network and reproduce the results of cc.

**Comment by anuragranj** [comment]
Yes, the training code is complete.
