### ISSUE TITLE
spatial_correlation_sampler

### ISSUE THREAD

**Issue by babahaji** [anuragranj/cc#8]
Hey, I got This error when I want to run code.
 import spatial_correlation_sampler_backend as correlation

lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

Cuda 10, gcc 7, pytorch-1.0

**Comment by anuragranj** [comment]
I looks like a problem with the correlation layer. Can you check if this library works for you?
https://github.com/ClementPinard/Pytorch-Correlation-extension

**Comment by babahaji** [comment]
I installed from source and using pip, checking requirements but none of them works. when I want to import them, give same error (undefined symbol):
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
Cuda compilation tools, release 10.0, V10.0.130

**Comment by anuragranj** [comment]
So, you do

```bash
pip install spatial-correlation-sampler
```
This passes. And then, when you import it in python,

```python
from spatial_correlation_sampler import spatial_correlation_sample
````
This fails?

**Comment by babahaji** [comment]
yes,
installation is fine but 
import torch
from spatial_correlation_sampler import SpatialCorrelationSampler 
fails

**Comment by anuragranj** [comment]
Could you raise the issue here:
https://github.com/ClementPinard/Pytorch-Correlation-extension/issues

**Comment by babahaji** [comment]
Done. BTW, Do you have any docker image for CC

**Comment by zmlshiwo** [comment]
Hi, I try to install spatial_correlation_sampler with command,
`pip3 install spatial_correlation_sampler`
I get the follows errors,
`error: command 'usr/local/cuda/bin/nvcc' failed with exit status 2`.
I use Ubuntu16.04, CUDA8.0, Python3.5, Pytorch1.0.1, GCC 5.4
Can you provide your version of CUDA, Python, Pytorch and GCC?
Thank you!

**Comment by zmlshiwo** [comment]
@anuragranj

**Comment by anuragranj** [comment]
@zmlshiwo I recommend you upgrade your cuda. As mentioned here:
https://github.com/ClementPinard/Pytorch-Correlation-extension

> This module needs compatible gcc version and CUDA to be compiled. Namely, CUDA 9.1 and below will need gcc5, while CUDA 9.2 and 10.0 will need gcc7 See [this issue](https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/1) for more information

**Comment by anuragranj** [comment]
@babahaji  I don't have any docker image. But, I just tested and it works with the following configuration:
pytorch1.0, cuda10.0 and gcc8/gcc7

Could you try gcc8?
Is `import torch` working for you? If not, there might be some problem with your torch installation.

**Comment by babahaji** [comment]
import torch is OK, I tested for both gcc8/gcc7 and get same error. here is my torch version. 
>>> import torch
>>> print(torch.__version__)
1.0.1.post2

**Comment by zmlshiwo** [comment]
@anuragranj Thank you. I will upgrade my cuda 8.0 to cuda 9.2.

**Comment by anuragranj** [comment]
Referenced here:
https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/15

and here:
https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/16

**Comment by xdr940** [comment]
> import torch is OK, I tested for both gcc8/gcc7 and get same error. here is my torch version.
> 
> > > > import torch
> > > > print(torch.**version**)
> > > > 1.0.1.post2

have your problem been solved?? I get the same error.

**Comment by xdr940** [comment]
version
gcc-7
cuda 9.2
ubuntu 18.04

**Comment by xdr940** [comment]
> Hey, I got This error when I want to run code.
> import spatial_correlation_sampler_backend as correlation
> 
> lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE
> 
> Cuda 10, gcc 7, pytorch-1.0

Have your problem been solved?? I got the same error 
gcc-7
cuda 9.2
ubuntu 18.04

**Comment by Ric4rdoLuna** [comment]
I have the same problem in Windows and Ubuntu.
