### ISSUE TITLE
run_inference.py pretrained  weight

### ISSUE THREAD

**Issue by babahaji** [anuragranj/cc#9]
When I want to run cc on my own dataset using run_inference.py I got following error.

python run_inference.py  --output-disp --pretrained ./downloads/geometry/dispnet_k.pth.tar --dataset-list ./output/test_files.txt --dataset-dir ./output/test_data --output-dir ./output/output --img-exts png
Traceback (most recent call last):
  File "run_inference.py", line 77, in <module>
    main()
  File "run_inference.py", line 37, in main
    disp_net.load_state_dict(weights['state_dict'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DispNetS:
        Missing key(s) in state_dict: "conv2.0.weight", "conv2.0.bias", “….

—————
where --pretrained “pretrained DispNet” weights are downloaded from:	
•	DispNet, PoseNet, MaskNet and FlowNet in joint unsupervised learning of depth, camera motion, optical flow and motion segmentation.

**Comment by anuragranj** [comment]
Oops. This is non-functional. You can change this line:
https://github.com/anuragranj/cc/blob/master/run_inference.py#L35
and replace DispNetS to DispResNet after importing it, and it should work.
